Update k8s-deploy.yml

diff --git a/.github/workflows/k8s-deploy.yml b/.github/workflows/k8s-deploy.yml
--- a/.github/workflows/k8s-deploy.yml
+++ b/.github/workflows/k8s-deploy.yml
@@ -112,10 +112,15 @@ jobs:
 
     - name: Set up AWS CLI
       run: |
-        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        unzip awscliv2.zip
-        sudo ./aws/install
-        aws --version
+        if ! command -v aws &> /dev/null; then
+          echo "AWS CLI not found, installing..."
+          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install
+        else
+          echo "AWS CLI is already installed, skipping installation."
+          aws --version
+        fi
 
     - name: Generate kubeconfig
       run: |
